---

- name: Jenkinsが依存しているパッケージをインストール
  apt: name={{ item }} state=installed
  with_items: jenkins.deb.dependencies

- name      : Jenkinsインストール
  apt       :
    name    : jenkins
    state   : installed
  register  : jenkins_install

- name      : Jenkins起動
  service   :
    name    : jenkins
    state   : started
    enabled : yes

