---
- name      : ntpインストール
  apt       :
    name    :
      - ntp
      - ntpdate
    state   : installed

- name      : テンプレートを/etc/ntp.confにコピー
  notify    : ntp再起動
  template  :
    src     : ntp.conf.j2
    dest    : /etc/ntp.conf

# ntpd停止中の時しかntpdateできない
# - name      : ntpdate実行 (ntp停止中の場合)
#   command   : ntpdate {{ ntp_servers.0 }}       # see group_vars/all.yml
#   when      : ntp_started

- name      : ntp起動
  service   :
    name    : ntp
    state   : restarted
    enabled : yes
  register  : ntp_started


