---
- name        : /etc/localtime を {{ timezone }} に
  file        : src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link

- name: set /etc/localtime
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link

- name: set /etc/timezone
  template: src=templates/timezone dest=/etc/timezone
  notify: update tzdata