---
- name                  : Install dependencies
  apt                   :
    name                : "{{ item }}"
    state               : present
    install_recommends  : no
  with_items            : rbenv_packages   # see default/main.yml
